app:
  name: "Insurance Calculator"
  scheme: "http"
  host: "localhost:3000"
  relative_url_root: "/"
  full_url: "http://localhost:3000/"

# Overwrite this in production
secret_token: ''

urn_namespaces:
- "urn:biola:insurance-calculator:"
- "urn:biola:apps:all:"

cas:
  url: "https://login.biola.edu/cas"

banner_app:
  url: "https://bannertest.biola.edu"
